
Loaded metadata for 7 speakers from CSV.
Found 2 meetings to process.

--- STEP 1: ENROLLING SPEAKERS ---
Found 7 speaker folders on disk.
  -> WARNING: Skipping folder 'TV HDQT Takeo Shimotsu' because it contains no .wav files.
Enrolling speaker 'BINHTM' from folder 'CT HDQT Tran Minh Binh' with 10 samples...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 976, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/test_client/test_api.py", line 123, in run_full_test
    response_json = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 980, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/test_client/test_api.py", line 216, in <module>
    run_full_test()
  File "/test_client/test_api.py", line 124, in run_full_test
    except JSONDecodeError:
NameError: name 'JSONDecodeError' is not defined
